<!-- <template>
  <div class="product">
    <h1>This is a product page</h1>
  </div>
</template> -->

<template>
  <div class="product">
    <h1>This is a product page</h1>
    <h2>可惡 吵死了</h2>
    <label for="myInput">我沒有說謊，我何必說謊</label>
    <input id="myInput" type="lier" />
    <p>zhuuu test</p>
    <span>hui test</span>
    <p>花花公子帥章魚 test</p>
    <div>帽子給我好嗎</div>
    <p>zhu aaa</p>
  </div>
</template>

<style lang="scss" scoped>
@import "@/assets/scss/style.scss";
@media (min-width: 1024px) {
  .about {
    min-height: 100vh;
    display: flex;
    align-items: center;
  }
}
</style>
